apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: delighted-jackal-python
  janus-idp.io/tekton: delighted-jackal-python
  backstage.io/kubernetes-id: delighted-jackal-python
  backstage.io/kubernetes-namespace: rhtap-integ 
  app.kubernetes.io/part-of: delighted-jackal-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
